library(devtools)
devtools::document("x:/ciTools/ciTools")
devtools::build("x:/ciTools/ciTools")
devtools::install("x:/ciTools/ciTools", dependencies = TRUE)
library(ciTools)
devtools::load_all("x:/ciTools/ciTools")
devtools::check("x:/ciTools/ciTools")
