---
title: Using ciTools with Generalized Linear Models
author: John Haman
date: November 2, 2017
output:
   html_document:
     toc: true
---

```{r }
library(tidyverse)
library(ciTools)
set.seed(20171102)
```

## The Generalized Linear Model

Generalized linear models are an extension of linear models that
seek to accomodate certain types of non-linear relationships. The
manner in which the non-linear relationship is addressed also
allows users to perform inferences on data that are not strictly
continuous. GLMs are the most common model type that allow for a
non-linear relationship between the response variable $y$ and
covariates $X$. Recall that linear regression directly predicts a
continuous response from the linear predictor $X \beta$. A GLM
consists of the following components:

1. A response vector $y = (y_1, \ldots, y_n)$.

2. A linear predictor $X \beta$

3. A monotonic and differentiable link function $g$, which
transforms the linear predictor: $\hat{y} = g^{-1}(X \beta)$.

4. A response distribution: $f(y|\hat{y})$.

Other components, such as over dispersion parameters and off-set
terms are possible, but not common to all GLMs.

